# -*- coding: utf-8 -*-
"""Titanik Tahmin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTMd1HKNYsbx6X-0IgG6Efed1pnMx9T0
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Modeller
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Veri setini yükleme
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Hedef değişken
y = df['Survived']
X = df.drop('Survived', axis=1)

print("Veri Seti Yüklendi. İlk 5 satır:")
print(df.head())
print("\nVeri Tipleri:")
print(df.info())

# Feature Engineering: FamilySize
X['FamilySize'] = X['SibSp'] + X['Parch'] + 1
# Pclass, Sex, Age, Fare, Embarked, FamilySize
features = ['Pclass', 'Sex', 'Age', 'Fare', 'FamilySize', 'Embarked']
X = X[features]

# Numerik ve Kategorik Sütunları Ayırma
numeric_features = ['Age', 'Fare', 'FamilySize']
categorical_features = ['Pclass', 'Sex', 'Embarked']

# Numerik Dönüştürücü
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # Eksik değerleri medyan ile doldur
    ('scaler', StandardScaler())                    # Ölçekleme (Standardizasyon)
])

# Kategorik Dönüştürücü
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')), # Eksik değerleri en sık olanla doldur (Embarked)
    ('onehot', OneHotEncoder(handle_unknown='ignore'))     # One-Hot Encoding
])

# Sütun Dönüştürücü (ColumnTransformer)
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

print("\nÖn İşleme Boru Hattı Tanımlandı.")

# Veriyi Eğitim ve Test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nVeri Ayırma (Hold-out): Eğitim Boyutu = {len(X_train)}, Test Boyutu = {len(X_test)}")

# Kullanılacak Modellerin Listesi
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "KNN": KNeighborsClassifier(),
    "SVC": SVC(probability=True, random_state=42), # BURAYI DEĞİŞTİRİN
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Gaussian NB": GaussianNB(),
    "Random Forest (Ensemble)": RandomForestClassifier(random_state=42),
    "Gradient Boosting (Ensemble)": GradientBoostingClassifier(random_state=42)
}

results_holdout = {}

print("\n--- a) Dışarıda Tutma (Hold-out) Sonuçları ---")
for name, model in models.items():
    # Boru hattını oluşturma (ön işleme + model)
    full_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                    ('classifier', model)])

    # Modeli eğitme
    full_pipeline.fit(X_train, y_train)

    # Test setinde tahmin yapma
    y_pred = full_pipeline.predict(X_test)

    # Başarı skorunu hesaplama
    accuracy = accuracy_score(y_test, y_pred)
    results_holdout[name] = accuracy
    print(f"{name}: Doğruluk = {accuracy:.4f}")

results_cv = {}
num_folds = 10

print(f"\n--- b) {num_folds}-Kat Çapraz Doğrulama Sonuçları ---")
for name, model in models.items():
    # Boru hattını oluşturma (ön işleme + model)
    full_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                    ('classifier', model)])

    # Çapraz doğrulama skorlarını hesaplama
    # scoring='accuracy' kullanarak başarı skorunu hesaplama
    scores = cross_val_score(full_pipeline, X, y, cv=num_folds, scoring='accuracy')

    # Ortalamayı kaydetme
    mean_accuracy = scores.mean()
    results_cv[name] = mean_accuracy
    print(f"{name}: Ort. Doğruluk = {mean_accuracy:.4f} (Std: {scores.std():.4f})")

print("\n--- Özet Karşılaştırma ---")

# Sonuçları DataFrame'e dönüştürerek daha okunaklı hale getirme
summary_df = pd.DataFrame({
    'Model': list(models.keys()),
    'Hold-out Accuracy': list(results_holdout.values()),
    f'{num_folds}-Fold CV Mean Accuracy': list(results_cv.values())
})

# Başarıya göre sıralama (Çapraz Doğrulama)
summary_df = summary_df.sort_values(by=f'{num_folds}-Fold CV Mean Accuracy', ascending=False).reset_index(drop=True)

print(summary_df)

import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc, RocCurveDisplay



# Tüm metrikleri depolamak için boş bir sözlük
all_metrics = {}

# Sınıflandırıcılar listesi
classifier_pipelines = {}
for name, model in models.items():
    classifier_pipelines[name] = Pipeline(steps=[('preprocessor', preprocessor),
                                                 ('classifier', model)])

print("Adım 1: Tüm Scikit-learn modelleri eğitiliyor...")
# Tüm Scikit-learn modellerini eğitim setinde eğitiyoruz
for name, pipeline in classifier_pipelines.items():
    pipeline.fit(X_train, y_train)

# YSA için veriyi ön işlemden geçirme
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)
input_shape = X_train_transformed.shape[1]

# Yapay Sinir Ağı (ANN) Modeli Tanımlama
model_ann = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(input_shape,)),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(1, activation='sigmoid') # İkili sınıflandırma için sigmoid
])

model_ann.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

# Modeli Epoch değeri >= 100 olacak şekilde eğitme
EPOCHS = 100
BATCH_SIZE = 32

print(f"\nAdım 2: Yapay Sinir Ağı (YSA) {EPOCHS} Epoch ile eğitiliyor...")
history = model_ann.fit(X_train_transformed, y_train,
                        epochs=EPOCHS,
                        batch_size=BATCH_SIZE,
                        validation_split=0.2, # Eğitim verisinin %20'si doğrulama için
                        verbose=0) # Eğitimin loglarını gösterme

# YSA için tahmin yapma
y_pred_ann_proba = model_ann.predict(X_test_transformed).ravel()
y_pred_ann = (y_pred_ann_proba > 0.5).astype(int)

# YSA metriklerini kaydetme
acc = accuracy_score(y_test, y_pred_ann)
prec = precision_score(y_test, y_pred_ann)
rec = recall_score(y_test, y_pred_ann)
f1 = f1_score(y_test, y_pred_ann)
cm = confusion_matrix(y_test, y_pred_ann)
roc_auc = auc(*roc_curve(y_test, y_pred_ann_proba)[:2])

all_metrics['Yapay Sinir Ağı (ANN)'] = {
    'Accuracy': acc, 'Precision': prec, 'Recall': rec, 'F1-Score': f1, 'Confusion Matrix': cm, 'ROC AUC': roc_auc, 'y_proba': y_pred_ann_proba
}

# ------------------------------------------------------------------------------
# YSA Eğitim Grafiği (a)
# ------------------------------------------------------------------------------

plt.figure(figsize=(14, 5))

# Kayıp (Loss) Grafiği
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Eğitim Kaybı')
plt.plot(history.history['val_loss'], label='Doğrulama Kaybı')
plt.title('Yapay Sinir Ağı: Eğitim ve Doğrulama Kaybı')
plt.xlabel('Epoch')
plt.ylabel('Kayıp Değeri')
plt.legend()
plt.grid(True)

# Başarı (Accuracy) Grafiği
plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Eğitim Başarısı')
plt.plot(history.history['val_accuracy'], label='Doğrulama Başarısı')
plt.title('Yapay Sinir Ağı: Eğitim ve Doğrulama Başarısı')
plt.xlabel('Epoch')
plt.ylabel('Başarı Değeri')
plt.legend()
plt.grid(True)

plt.show()

print("\nAdım 3: Tüm Modeller İçin Detaylı Metrikler ve Görselleştirmeler Hesaplama...")


for name, pipeline in classifier_pipelines.items():

    # Sınıf Tahmini (y_pred)
    y_pred = pipeline.predict(X_test)

    # Olasılık Tahmini (y_proba) - ROC/AUC için gerekli
    # SVC'de `probability=True` ayarlanmadıysa hata verebilir, bu yüzden kontrol etmeliyiz.
    if hasattr(pipeline.named_steps['classifier'], 'predict_proba'):
        y_proba = pipeline.predict_proba(X_test)[:, 1]
    elif name == "SVC":
        # SVC için proba hesaplamayı atla veya modelin probability=True ile yeniden eğitilmesi gerekir.
        # Basitlik için, SVC'yi bu adımda sadece sınıflandırma skorları ile değerlendiriyoruz.
        # Eğer y_proba gerekiyorsa, SVC'nin tanımını: SVC(probability=True, random_state=42) olarak değiştirmemiz gerekir.
        # Bu kod bloğunda, ROC/AUC'yi hesaplayamayacağımız varsayımıyla devam edelim.
        y_proba = None
    else:
        y_proba = None

    # Metrikleri Hesaplama
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    roc_auc = None
    if y_proba is not None:
        roc_auc = auc(*roc_curve(y_test, y_proba)[:2])

    all_metrics[name] = {
        'Accuracy': acc, 'Precision': prec, 'Recall': rec, 'F1-Score': f1, 'Confusion Matrix': cm, 'ROC AUC': roc_auc, 'y_proba': y_proba
    }

# ------------------------------------------------------------------------------
# Karışıklık Matrisleri (b)
# ------------------------------------------------------------------------------

print("\n--- Karışıklık Matrisleri (Confusion Matrices) ---")
fig, axes = plt.subplots(3, 3, figsize=(15, 15))
axes = axes.ravel()
fig.tight_layout(pad=3.0)

for i, (name, metrics) in enumerate(all_metrics.items()):
    ax = axes[i]
    cm = metrics['Confusion Matrix']
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax, cbar=False,
                xticklabels=['Öldü (0)', 'Hayatta Kaldı (1)'],
                yticklabels=['Öldü (0)', 'Hayatta Kaldı (1)'])
    ax.set_title(f'CM: {name}')
    ax.set_ylabel('Gerçek Değer')
    ax.set_xlabel('Tahmin Edilen Değer')

# Kullanılmayan boş alt grafiği gizleme
if len(all_metrics) < len(axes):
    for j in range(len(all_metrics), len(axes)):
        fig.delaxes(axes[j])
plt.show()

# ------------------------------------------------------------------------------
# Doğruluk, Duyarlılık, Özgüllük ve F1-skoru Tablosu (c)
# ------------------------------------------------------------------------------

# Özgüllük (Specificity) = Gerçek Negatif / (Gerçek Negatif + Yanlış Pozitif)
# Karışıklık Matrisi (CM) formatı: [[TN, FP], [FN, TP]]

def calculate_specificity(cm):
    tn, fp, fn, tp = cm.ravel()
    return tn / (tn + fp)

tabular_data = []
for name, metrics in all_metrics.items():
    cm = metrics['Confusion Matrix']
    specificity = calculate_specificity(cm)

    # Satır verilerini oluşturma
    row = {
        'Model': name,
        'Doğruluk (Accuracy)': metrics['Accuracy'],
        'Duyarlılık (Precision)': metrics['Precision'],
        'Geri Çağırma (Recall)': metrics['Recall'],
        'Özgüllük (Specificity)': specificity,
        'F1-Skoru': metrics['F1-Score'],
        'ROC AUC': metrics['ROC AUC']
    }
    tabular_data.append(row)

# Sonuçları DataFrame'e dönüştürme
results_df = pd.DataFrame(tabular_data)

# Başarıya göre sıralama
results_df = results_df.sort_values(by='Doğruluk (Accuracy)', ascending=False).reset_index(drop=True)

print("\n--- c) Detaylı Performans Metrikleri Tablosu ---")
# Ondalık basamakları sınırlayarak çıktı verme
print(results_df.round(4).to_markdown(index=False))


# ------------------------------------------------------------------------------
# Alıcı-İşlem Karakteristiği (ROC) Sonuçları (d)
# ------------------------------------------------------------------------------

print("\n--- d) Alıcı-İşlem Karakteristiği (ROC) ve AUC ---")

plt.figure(figsize=(10, 8))
plt.title('Alıcı-İşlem Karakteristiği (ROC) Eğrileri')

# Tüm modeller için ROC eğrilerini çizme
for name, metrics in all_metrics.items():
    y_proba = metrics['y_proba']
    roc_auc = metrics['ROC AUC']

    if y_proba is not None:
        fpr, tpr, _ = roc_curve(y_test, y_proba)
        plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.4f})')
    elif name == "SVC":
        # SVC için y_proba'yı hesaplamadığımızı belirten bir not
        print(f"Uyarı: {name} için olasılık tahmini yapılmadığından ROC eğrisi çizilemedi.")

plt.plot([0, 1], [0, 1], 'r--', label='Rastgele Tahmin (AUC = 0.50)')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Yanlış Pozitif Oranı (FPR)')
plt.ylabel('Doğru Pozitif Oranı (TPR - Geri Çağırma)')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc

print("\nAdım 4: 10-Katlı K-Fold Metrikleri, Matrisler ve ROC Eğrileri...")

# 1. K-Fold Ayarları
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
all_kfold_metrics = {}

# ROC çizimi için figür hazırlığı
plt.figure(figsize=(10, 8))
plt.title('10-Fold Çapraz Doğrulama: Ortalama ROC Eğrileri')

# 2. Her Algoritma İçin K-Fold Döngüsü
for name, pipeline in classifier_pipelines.items():

    fold_acc, fold_prec, fold_rec, fold_f1, fold_spec = [], [], [], [], []
    fold_cms = []

    # ROC için gerekli listeler
    tprs = []
    base_fpr = np.linspace(0, 1, 101)

    for train_index, test_index in skf.split(X, y):
        X_train_kf, X_test_kf = X.iloc[train_index], X.iloc[test_index]
        y_train_kf, y_test_kf = y.iloc[train_index], y.iloc[test_index]

        pipeline.fit(X_train_kf, y_train_kf)
        y_pred_kf = pipeline.predict(X_test_kf)

        # Metrikleri hesapla
        cm_kf = confusion_matrix(y_test_kf, y_pred_kf)
        fold_cms.append(cm_kf)
        fold_acc.append(accuracy_score(y_test_kf, y_pred_kf))
        fold_prec.append(precision_score(y_test_kf, y_pred_kf, zero_division=0))
        fold_rec.append(recall_score(y_test_kf, y_pred_kf))
        fold_f1.append(f1_score(y_test_kf, y_pred_kf))

        tn, fp, fn, tp = cm_kf.ravel()
        fold_spec.append(tn / (tn + fp) if (tn + fp) > 0 else 0)

        # ROC / AUC Hesaplama (Olasılık tahmini varsa)
        if hasattr(pipeline.named_steps['classifier'], 'predict_proba'):
            y_proba_kf = pipeline.predict_proba(X_test_kf)[:, 1]
            fpr, tpr, _ = roc_curve(y_test_kf, y_proba_kf)
            # Eğriyi interpole et (ortalama almak için)
            tpr_interp = np.interp(base_fpr, fpr, tpr)
            tpr_interp[0] = 0.0
            tprs.append(tpr_interp)

    # Ortalamaları hesapla
    avg_tpr = np.mean(tprs, axis=0) if tprs else None
    avg_auc = auc(base_fpr, avg_tpr) if avg_tpr is not None else None

    all_kfold_metrics[name] = {
        'Accuracy': np.mean(fold_acc),
        'Precision': np.mean(fold_prec),
        'Recall': np.mean(fold_rec),
        'F1-Score': np.mean(fold_f1),
        'Specificity': np.mean(fold_spec),
        'ROC AUC': avg_auc,
        'Mean_CM': np.mean(fold_cms, axis=0).astype(int)
    }

    # ROC Eğrisini Grafiğe Ekle
    if avg_tpr is not None:
        plt.plot(base_fpr, avg_tpr, label=f'{name} (Ort. AUC = {avg_auc:.4f})')

# ROC Grafik Detayları
plt.plot([0, 1], [0, 1], 'r--', label='Rastgele (AUC = 0.50)')
plt.xlabel('Yanlış Pozitif Oranı (FPR)')
plt.ylabel('Doğru Pozitif Oranı (TPR)')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

# ------------------------------------------------------------------------------
# 10-Fold Karışıklık Matrisleri (Görselleştirme)
# ------------------------------------------------------------------------------
print("\n--- 10-Fold Ortalama Karışıklık Matrisleri ---")
fig, axes = plt.subplots(3, 3, figsize=(15, 15))
axes = axes.ravel()
fig.tight_layout(pad=3.0)

for i, (name, metrics) in enumerate(all_kfold_metrics.items()):
    ax = axes[i]
    sns.heatmap(metrics['Mean_CM'], annot=True, fmt='d', cmap='Greens', ax=ax, cbar=False,
                xticklabels=['Öldü (0)', 'Hayatta Kaldı (1)'],
                yticklabels=['Öldü (0)', 'Hayatta Kaldı (1)'])
    ax.set_title(f'10-Fold CM: {name}')

if len(all_kfold_metrics) < len(axes):
    for j in range(len(all_kfold_metrics), len(axes)):
        fig.delaxes(axes[j])
plt.show()

# ------------------------------------------------------------------------------
# 10-Fold Başarı Metrikleri Tablosu
# ------------------------------------------------------------------------------
kfold_tabular_data = []
for name, metrics in all_kfold_metrics.items():
    kfold_tabular_data.append({
        'Algoritma': name,
        '10-Fold Acc': metrics['Accuracy'],
        '10-Fold Prec': metrics['Precision'],
        '10-Fold Rec': metrics['Recall'],
        '10-Fold Spec': metrics['Specificity'],
        '10-Fold F1': metrics['F1-Score'],
        '10-Fold AUC': metrics['ROC AUC']
    })

kfold_results_df = pd.DataFrame(kfold_tabular_data)
kfold_results_df = kfold_results_df.sort_values(by='10-Fold Acc', ascending=False).reset_index(drop=True)

print("\n--- Adım 4: 10-Fold Detaylı Performans Tablosu (ROC AUC Dahil) ---")
print(kfold_results_df.round(4).to_markdown(index=False))

import joblib


best_model_name = "Gradient Boosting (Ensemble)" # Veya en yüksek skorlu modelin adı
best_pipeline = classifier_pipelines[best_model_name]


joblib.dump(preprocessor, 'preprocessor.pkl')
joblib.dump(best_pipeline, 'best_model_pipeline.pkl')

print(f"Başarılı! {best_model_name} modeli ve ön işlemci kaydedildi.")

import pandas as pd
from statsmodels.stats.contingency_tables import mcnemar
import numpy as np

# Önceki adımlardan gelen eğitilmiş pipeline'lar ve YSA modeli
model1_name = "Random Forest (Ensemble)"
model2_name = "Yapay Sinir Ağı (ANN)"

# Modelleri ve test verilerini hazırlama
pipeline_rf = classifier_pipelines[model1_name] # Eğitilmiş RF pipeline'ı
model_ann = model_ann # Eğitilmiş YSA modeli



# Model 1 (RF) Tahminleri
y_pred_model1 = pipeline_rf.predict(X_test)

# Model 2 (YSA) Tahminleri

y_pred_model2_proba = model_ann.predict(X_test_transformed).ravel()
y_pred_model2 = (y_pred_model2_proba > 0.5).astype(int)

# Gerçek Değerler
y_true = y_test.values

# Karşılaştırma Matrisini oluşturma
n01 = np.sum((y_pred_model1 != y_true) & (y_pred_model2 == y_true)) # RF Yanlış, YSA Doğru
n10 = np.sum((y_pred_model1 == y_true) & (y_pred_model2 != y_true)) # RF Doğru, YSA Yanlış
n11 = np.sum((y_pred_model1 == y_true) & (y_pred_model2 == y_true)) # İkisi de Doğru
n00 = np.sum((y_pred_model1 != y_true) & (y_pred_model2 != y_true)) # İkisi de Yanlış

# McNemar Tablosu:
# Satırlar: Model 1'in tahmini (Doğru, Yanlış)
# Sütunlar: Model 2'nin tahmini (Doğru, Yanlış)

contingency_table = np.array([[n11, n01],
                              [n10, n00]])

print(f"\n--- McNemar Çapraz Sınıflandırma Tablosu ({model1_name} vs {model2_name}) ---")
df_cont = pd.DataFrame(contingency_table,
                       index=[f'{model1_name} Doğru', f'{model1_name} Yanlış'],
                       columns=[f'{model2_name} Doğru', f'{model2_name} Yanlış'])
print(df_cont)

# Tablo Yorumu:
# [Satır 1, Sütun 2] (n01): Model 2'nin üstün geldiği durumlar (M1 yanlış, M2 doğru)
# [Satır 2, Sütun 1] (n10): Model 1'in üstün geldiği durumlar (M1 doğru, M2 yanlış)

# McNemar testi (varsayılan olarak düzeltme (correction=True) kullanır)
result = mcnemar(contingency_table, exact=False, correction=True) # Chi-Square yaklaşımı kullanıldı

print("\n--- McNemar Testi Sonuçları ---")
print(f"Ki-Kare Değeri (Statistic): {result.statistic:.4f}")
print(f"P-değeri (P-value): {result.pvalue:.4f}")

# Yorumlama
alpha = 0.05
print(f"\nİstatistiksel Anlamlılık Düzeyi (alpha): {alpha}")

if result.pvalue < alpha:
    print(f"Sonuç: P-değeri ({result.pvalue:.4f}) < {alpha} olduğundan, **Boş Hipotez (H0) reddedilir.**")
    print(f"Yorum: {model1_name} ve {model2_name} modellerinin performansları arasında istatistiksel olarak **anlamlı bir fark** vardır.")
    if n01 > n10:
        print(f"Üstün Model: {model2_name} ({model2_name}, {model1_name}'dan daha az hata yapmıştır.)")
    else:
        print(f"Üstün Model: {model1_name} ({model1_name}, {model2_name}'dan daha az hata yapmıştır.)")
else:
    print(f"Sonuç: P-değeri ({result.pvalue:.4f}) >= {alpha} olduğundan, **Boş Hipotez (H0) kabul edilir.**")
    print(f"Yorum: {model1_name} ve {model2_name} modellerinin performansları arasında istatistiksel olarak **anlamlı bir fark yoktur**.")

# Gerekli kütüphane (önceki adımlardan zaten yüklenmiş olmalı)
import pandas as pd
import numpy as np

# --- EN İYİ MODELİ SEÇME ---
# Önceki analiz tablonuza göre en iyi modeli seçin.
# Varsayım: Gradient Boosting en iyisi.
BEST_MODEL_NAME = "Gradient Boosting (Ensemble)"
best_pipeline = classifier_pipelines[BEST_MODEL_NAME]

# --- GİRDİ VERİLERİNİ TEMİZLEME VE DÖNÜŞTÜRME FONKSİYONU ---
def get_user_prediction(pclass, sex, age, fare, sibsp, parch, embarked):
    """
    Kullanıcıdan alınan ham verileri alır, tahmin yapar ve sonucu yorumlar.
    """

    # Yeni veri girişi için DataFrame oluşturma
    new_data = pd.DataFrame({
        'Pclass': [pclass],
        'Sex': [sex],
        'Age': [age],
        'Fare': [fare],
        'SibSp': [sibsp], # FamilySize hesaplamak için gerekli
        'Parch': [parch], # FamilySize hesaplamak için gerekli
        'Embarked': [embarked]
    })

    # Feature Engineering: FamilySize hesaplama
    new_data['FamilySize'] = new_data['SibSp'] + new_data['Parch'] + 1

    # Sadece modelin kullandığı sütunları seçme (önceki Adım 2'deki tanıma uymalı)
    features_for_model = ['Pclass', 'Sex', 'Age', 'Fare', 'FamilySize', 'Embarked']
    input_data = new_data[features_for_model]

    # --- TAHMİN ADIMLARI ---

    # 1. Olasılık Tahmini (predict_proba)
    # [0] = Ölüme Olasılığı, [1] = Hayatta Kalma Olasılığı
    proba = best_pipeline.predict_proba(input_data)[0]

    survival_proba = proba[1]
    death_proba = proba[0]

    # 2. Sınıf Tahmini (predict)
    prediction = best_pipeline.predict(input_data)[0]

    # --- SONUÇ YORUMLAMA ---

    if prediction == 1:
        result_text = "HAYATTA KALIR"
        probability = survival_proba
    else:
        result_text = "ÖLÜR"
        probability = death_proba

    return probability, result_text, survival_proba, death_proba

try:
    # Kaydedilen Model ve Ön İşleme Adımlarını Yükle
    preprocessor = joblib.load('preprocessor.pkl')
    best_pipeline = joblib.load('best_model_pipeline.pkl')
    BEST_MODEL_NAME = "Gradient Boosting (Ensemble)"
    print(f"Model yüklemesi başarılı: {BEST_MODEL_NAME}")

except FileNotFoundError:
    print("HATA: Model dosyaları (preprocessor.pkl veya best_model_pipeline.pkl) bulunamadı.")
    print("Lütfen önceki adımlardaki model kaydetme kodunu çalıştırdığınızdan emin olun.")

except Exception as e:
    print(f"Yükleme sırasında beklenmeyen bir hata oluştu: {e}")

def titanic_survival_predictor(pclass, sex, age, sibsp, parch, fare, embarked):
    """
    Gradio arayüzünden gelen ham verileri alır, tahmin yapar ve sonucu yorumlar.
    """

    # 1. Feature Engineering: FamilySize hesaplama
    family_size = sibsp + parch + 1

    # 2. Yeni veri girişi için DataFrame oluşturma
    # Not: Sütun isimleri ve sırası, modelin beklediği özelliklerle aynı olmalıdır.
    input_data = pd.DataFrame({
        'Pclass': [pclass],
        'Sex': [sex],
        'Age': [age],
        'Fare': [fare],
        'FamilySize': [family_size], # Modelin kullandığı yeni özellik
        'Embarked': [embarked]
    }, index=[0])

    # Modelin kullandığı orijinal özellik listesini kullan
    features_for_model = ['Pclass', 'Sex', 'Age', 'Fare', 'FamilySize', 'Embarked']
    input_data = input_data[features_for_model]

    # 3. Tahmin Yapma (Pipeline hem ön işleme hem tahmin yapar)
    proba = best_pipeline.predict_proba(input_data)[0]
    prediction = best_pipeline.predict(input_data)[0]

    survival_proba = proba[1] * 100 # Yüzdelik için *100
    death_proba = proba[0] * 100    # Yüzdelik için *100

    # 4. Sonuç Metnini Oluşturma
    if prediction == 1:
        result_text = f"✅ **HAYATTA KALIR** (Hayatta Kalma Olasılığı: %{survival_proba:.2f})"
        color = "green"
    else:
        result_text = f"❌ **ÖLÜR** (Ölme Olasılığı: %{death_proba:.2f})"
        color = "red"

    # HTML ile renklendirilmiş çıktı döndürme
    html_output = f"<h1 style='color: {color}; text-align: center;'>{result_text}</h1>"
    html_output += f"<p style='text-align: center; font-size: 1.2em;'>Detay: Hayatta Kalma: %{survival_proba:.2f} | Ölüm: %{death_proba:.2f}</p>"

    return html_output

import gradio as gr

# Gradio Arayüzü Giriş Bileşenleri
inputs = [
    gr.Dropdown(label="Yolcu Sınıfı (Pclass)", choices=[1, 2, 3], value=3),
    gr.Radio(label="Cinsiyet (Sex)", choices=['male', 'female'], value='male'),
    gr.Slider(label="Yaş (Age)", minimum=0, maximum=80, step=1, value=30),
    gr.Slider(label="Kardeş/Eş Sayısı (SibSp)", minimum=0, maximum=8, step=1, value=0),
    gr.Slider(label="Ebeveyn/Çocuk Sayısı (Parch)", minimum=0, maximum=6, step=1, value=0),

    # GÜNCELLENMİŞ BİLET ÜCRETİ (FARE) BİLEŞENİ
    # Sınırlar (0.0'dan 520.0'a) eklenmiştir.
    gr.Number(label="Bilet Ücreti (Fare) ($)", minimum=0.0, maximum=520.0, value=30.0),

    gr.Dropdown(label="Biniş Limanı (Embarked)", choices=['C', 'Q', 'S'], value='S')
]

# Gradio Arayüzü Çıkış Bileşeni (HTML formatında gösterim için)
output = gr.HTML(label="Tahmin Sonucu")

# Gradio Arayüzünü Tanımlama
# Not: BEST_MODEL_NAME değişkeninin önceki hücrelerde tanımlandığı varsayılmaktadır.
title = "🚢 Titanic Hayatta Kalma Tahmin Motoru"
description = f"Yolcu bilgilerini girerek **{BEST_MODEL_NAME}** modeli ile hayatta kalma olasılığını hesaplayın."
article = "McNemar testi, Karışıklık Matrisleri ve ROC/AUC analizleri ile test edilmiş yüksek performanslı sınıflandırma modeli."

iface = gr.Interface(
    fn=titanic_survival_predictor,  # Tahmin fonksiyonunuzun adı
    inputs=inputs,
    outputs=output,
    title=title,
    description=description,
    article=article,
    allow_flagging='never'
)
